import Anthropic from '@anthropic-ai/sdk'
import type { VercelRequest, VercelResponse } from '@vercel/node'

const SYSTEM_PROMPT = `You are a professional strength and conditioning coach. The user will describe the training program they want.

Return ONLY valid JSON with this exact structure, no other text, no markdown fences:
{
  "name": "Program Name",
  "weeks": [
    {
      "weekNumber": 1,
      "days": [
        {
          "label": "Day A – Push",
          "exercises": [
            { "name": "Bench Press", "sets": 4, "reps": "8-10", "restSecs": 90 }
          ]
        }
      ]
    }
  ]
}

Rules:
- Include all requested weeks in full (do not abbreviate or say "repeat")
- Apply progressive overload across weeks (increase sets or reps gradually)
- Keep exercises realistic, safe, and appropriate for the stated goal
- restSecs should be a number (e.g. 60, 90, 120, 180)
- reps should be a string like "8-10", "5", or "12-15"
- Do not include IDs — those are generated by the app`

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' })
    return
  }

  const { prompt } = req.body as { prompt?: string }
  if (!prompt || typeof prompt !== 'string' || prompt.trim().length === 0) {
    res.status(400).json({ error: 'prompt is required' })
    return
  }

  try {
    const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })

    const message = await client.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 4096,
      system: SYSTEM_PROMPT,
      messages: [{ role: 'user', content: prompt.trim() }],
    })

    const text = message.content[0].type === 'text' ? message.content[0].text : ''

    // Strip markdown fences if present
    const stripped = text.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '').trim()

    let program
    try {
      program = JSON.parse(stripped)
    } catch {
      // Try to extract JSON object if there's surrounding text
      const match = stripped.match(/(\{[\s\S]*\})/)
      if (!match) throw new Error('No valid JSON found in response')
      program = JSON.parse(match[1])
    }

    res.status(200).json(program)
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error'
    res.status(500).json({ error: message })
  }
}
